--문제1
--SQL 응용
--김용현
SET SERVEROUTPUT ON;
DECLARE
BEGIN
    DBMS_OUTPUT.PUT_LINE('SQL 응용');
    DBMS_OUTPUT.PUT_LINE('김용현');
END;
/
--문제2
SET SERVEROUTPUT ON;
DECLARE
    SONNO EMP.EMPNO%TYPE;
    SONNAME EMP.ENAME%TYPE;
    SONDEPTNO EMP.DEPTNO%TYPE;
BEGIN
    SELECT EMPNO, ENAME, DEPTNO INTO SONNO, SONNAME, SONDEPTNO FROM EMP
    WHERE ENAME = 'TURNER';
    DBMS_OUTPUT.PUT_LINE(' 사원번호  이름  부서번호');
    DBMS_OUTPUT.PUT_LINE('-------------------------');
    DBMS_OUTPUT.PUT_LINE(SONNO||'   '||SONNAME||'  '||SONDEPTNO);
END;
/

--문제3
SET SERVEROUTPUT ON;
DECLARE
    SONEMP EMP%ROWTYPE;
    SONDNAME VARCHAR2(14);
BEGIN
    SELECT * INTO SONEMP FROM EMP
    WHERE ENAME = 'TURNER';
    IF (SONEMP.DEPTNO = 10) THEN
        SONDNAME := 'ACCOUNTING';
    ELSIF (SONEMP.DEPTNO = 20) THEN
        SONDNAME := 'CLERK';
    ELSIF (SONEMP.DEPTNO = 30) THEN
        SONDNAME := 'SLAES';
    ELSIF (SONEMP.DEPTNO = 40) THEN
        SONDNAME := 'OPERATIONS';
    ELSE
        SONDNAME := 'PLANNING';
    END IF;
    DBMS_OUTPUT.PUT_LINE(' 사원번호 이름 부서번호 부서명');
    DBMS_OUTPUT.PUT_LINE(' ---------------------------');
    DBMS_OUTPUT.PUT_LINE(SONEMP.EMPNO||'   '||SONEMP.ENAME||'  '||SONEMP.DEPTNO||'   '||SONDNAME);
END;    
/

--문제4
SET SERVEROUTPUT ON;
DECLARE
    NUM NUMBER := 0;
    I NUMBER :=0;
BEGIN
    WHILE (NUM < 200) 
    LOOP
        NUM := NUM + 1;
        I := I+NUM;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('총합='||I);
END;
/
