--문제1
--SQL 활용
--김용현

--문제2
SELECT * FROM EMP
ORDER BY SAL DESC, ENAME DESC;

--문제3
INSERT INTO DEPT VALUES(50,'Planning','Seoul');
SELECT * FROM DEPT;

--문제4
SELECT DEPTNO, MAX(SAL), MIN(SAL) FROM EMP
GROUP BY DEPTNO;

--문제5
SELECT DEPTNO, MAX(SAL) FROM EMP
group by DEPTNO
HAVING MAX(SAL) >= 3800;

--문제6
SELECT EMP.EMPNO, EMP.ENAME, DEPT.DEPTNO, DEPT.DNAME
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

--문제7
SELECT DNAME FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'SMITH');

--문제8
SELECT EMPNO, ENAME, JOB, SAL FROM EMP
WHERE SAL < (SELECT SAL FROM EMP WHERE EMPNO = 7654);

--문제9
SELECT DEPTNO, MIN(SAL) FROM EMP
GROUP BY DEPTNO
HAVING MIN(SAL) > (SELECT MIN(SAL) FROM EMP WHERE DEPTNO = 20);

--문제10
SELECT ENAME, SAL, DEPTNO FROM EMP
WHERE SAL> ALL(SELECT SAL FROM EMP WHERE DEPTNO = 30);







