--문항1
--데이터베이스 요구사항 분석
--김용현

--문항2
CREATE TABLE GoodsInfo (
proCode CHAR(5) primary key,
proName VARCHAR2(30) NOT NULL,
price NUMBER(8) NOT NULL,
maker VARCHAR2(25) NOT NULL);
commit;

--문항3
INSERT INTO GOODSINFO VALUES(1001,'냉장고',1800000,'SM');
INSERT INTO GOODSINFO VALUES(1002,'세탁기',550000,'LN');
INSERT INTO GOODSINFO VALUES(1003,'HDTV',280000,'HP');
INSERT INTO GOODSINFO VALUES(1004,'전자레인지',230000,'SM');
INSERT INTO GOODSINFO VALUES(1005,'오디오',770000,'LN');
INSERT INTO GOODSINFO VALUES(1006,'PC',880000,'HP');

--문항4
SELECT proCode AS 상품코드, proName AS 상품명, price AS 가격, maker AS 제조사 FROM GOODSINFO;
SELECT * FROM GOODSINFO;

--문항5
DESC GOODSINFO;

--문항6
SELECT SUM(PRICE) AS "모든 상품 가격 합" FROM GOODSINFO;

--문항7
ALTER TABLE GOODSINFO
ADD (salePrice NUMBER(8));
DESC GOODSINFO;

--문항8
SELECT proName AS 상품명, price AS 가격 FROM GOODSINFO
WHERE PRICE >= 700000 ;

--문항9
SELECT proName AS 상품명, price AS 가격 FROM GOODSINFO
WHERE proCode NOT IN (1002,1003);

--문항10
SELECT * FROM GOODSINFO
WHERE proName = 'PC';